version: "3.9"

services:
  triton:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rubert-triton
    ports:
      - "8000:8000"  
      - "8001:8001"  
      - "8002:8002"  
    profiles: ["cpu"]
    restart: unless-stopped

  triton-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rubert-triton-gpu
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    profiles: ["gpu"]
    restart: unless-stopped
