
version: "3.9"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    environment:
      - HOST=0.0.0.0
      - PORT=8080

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:80"
    depends_on:
      - api
